name: stitch_photo_app
description: This project is stitching of two photos
version: 0.0.2
homepage: https://github.com/kaangms/stitch_photo_app

environment:
  sdk: ">=2.18.6 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  plugin:
    platforms:
      ios:
        pluginClass: StitchPhotoAppPlugin
